apiVersion: apps/v1
kind: Deployment

metadata:
  name: httpd-deployment
  labels:
    app: httpd

spec:
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80

  replicas: 10

  selector:
    matchLabels:
      app: httpd 

